### ISSUE TITLE
Allow disable screenshot on failure

### ISSUE THREAD

**Issue by psyren89** [TestFX/TestFX#178]
Not much to say here, I'd just like to be able to disable screenshots until the test suite is ready. Currently struggling to get things set up in my project and having several MB of screenshots produced each run is getting tiresome to delete.

**Comment by hastebrot** [comment]
Hi! Would a JVM property (e.g. `-Dtestfx.screenshotOnError=false`) be sufficient for your use case?

**Comment by psyren89** [comment]
Ideally, a small method like `setTakeScreenshotOnFailure(boolean)` would do the trick.
Cheers!

**Comment by brcolow** [comment]
Closing because:

* It is unclear if this an issue about testfx-legacy or not.
* If it is, then closing because testfx-legacy is unmaintained.
* If it isn't, then we already default to not taking screenshots and only do so when an error message mapper (constructed via `DebugUtils`) captures screenshots.
