### ISSUE TITLE
How can i queue my testcase

### ISSUE THREAD

**Issue by Freemanhack** [TestFX/TestFX#291]
when i try to make testcase for test my project i write method like these

@Test
Case0a_Insert_Default(){Blah blah blah........}
@Test
case0b_Insert_Mandatory_Only(){Blah blah blah........}
@Test
case0c_Insert_NotMandatory_Only(){Blah blah blah........}

but after press project Test why IDE call testcase randomly like these "Case0c,Case0a,Case0b" or these "Case0b,Case0c,Case0a" 

How I can queue test case to be "Case0a,Case0b,Case0c"

Thank you in advanced for your help
Sorry for Bad English

**Comment by JordanMartinez** [comment]
@Freemanhack Your question sounds like it is more about JUnit than TestFX. JUnit doess't seem to allow you to do that. See [this StackOverflow question](https://stackoverflow.com/questions/3693626/how-to-run-test-methods-in-specific-order-in-junit4) and [this other question](https://stackoverflow.com/questions/34456739/how-do-i-define-an-order-to-run-junit-tests-in-intellij)

My guess is you'd need to put all three of those tests into one method.

Otherwise, you might want to consider using Spock (See a [quick guide here](http://thejavatar.com/testing-with-spock/) and [some examples here](https://github.com/spockframework/spock-example)) and it's `@Stepwise` annotation. That will execute the tests in the order you list them

**Comment by hastebrot** [comment]
One answer in the StackOverflow question @JordanMartinez linked says you can use `@FixMethodOrder(MethodSorters.NAME_ASCENDING)` to prevent the JUnit runner randomly execute your tests. The main point of having a random execution order is to promote independent test methods, as the answer points out.

**Comment by Freemanhack** [comment]
Extremely Thank you  for your answer

**Comment by JordanMartinez** [comment]
And thanks to @hastebrot for correcting my explanation. I use Spock and Groovy, so JUnit's configurations aren't very familiar to me.
