### ISSUE TITLE
write() in a headless setup. 

### ISSUE THREAD

**Issue by sstangle73** [TestFX/TestFX#304]
I am testing my code in a headless setup modeled after: http://stackoverflow.com/a/35309920/1124014

But it seems like my calls to write(String) are doing nothing and thus my tests fail. 

Any advice? Running with Java 8U91 TestFx 4.0.4Alpha Monocle 1.8.0_20 and junit 4

**Comment by hillam** [comment]
+1

**Comment by belu** [comment]
@sstangle73 @hillam What worked for me was something like that: https://gist.github.com/belu/828b9a333a29345fb2c864fd4e8afdae

**Comment by bbqf** [comment]
Same here. 

It's giving me lots of headache as the tests are failing from time to time. 

I'm trying to investigate the issue - unfortunately the tests never fail when started one by one, however I checked with screenshots that when they do, it's due to write() doing nothing, focus is set correctly.

**Comment by jcornaz** [comment]
Any update on this issue ?

**Comment by brcolow** [comment]
I added a test that uses `write` and it passes on the headless builds. Am I missing something?

**Comment by jcornaz** [comment]
No I don't think you're missing anything. I think it actually works.

I asked for update, because I had some issue that I wondered if they could be related to this topic. But it turned out they are not. My tests using `write` now constantly pass, even in headless setup.

In my opinion, adding the test proves this actually works. Thanks for adding it.
