### ISSUE TITLE
Method getParameters of JavaFX Application class suddenly returns null in the newest version of TestFX

### ISSUE THREAD

**Issue by VeryLazyBoy** [TestFX/TestFX#380]
I noticed that in 4.0.6-alpha, `getParameters` of `javafx.application.Application` has changed its behavior. In previous version, `getParameters` will return a empty `Application.Parameters` object when there is no parameter passed to application, however, after using the latest version of TestFX, it seems that a null value will be returned which causes some problems in my project.

**Comment by brcolow** [comment]
This is indeed the case and it is because the Parameters were being passed on in `ToolkitServiceImpl.java` thusly:

```java
private void registerApplicationParameters(Application application,		
                                            String... applicationArgs) {		
     ParametersImpl parameters = new ParametersImpl(applicationArgs);		
     ParametersImpl.registerParameters(application, parameters);		
}
```

Where `ParametersImpl` is `com.sun.javafx.application.ParametersImpl`. Because this is in the private API I removed this for Java 9 compatibility. We have two possible approaches to rectify this:

1.) Add the `ParametersImpl` class to the JDK 9 `--add-exports` argument as we currently do for `javafx.graphics/com.sun.glass.ui=ALL-UNNAMED`.
2.) See if it is possible, perhaps using reflection, to register the application startup parameters without having compile-time dependencies on classes in the "private API".

I will investigate `2.)` for now, but discussion is very much welcome.

**Comment by VeryLazyBoy** [comment]
@brcolow , thanks for your classification. I am just curious about will TestFX keep the current behavior of `getParameter`, i.e., returning null if there are no parameters passed to application? Or, are you going to find a way to resolve the dependencies of private API and revert the behavior of `getParameter` back in the future versions of TestFX?

**Comment by brcolow** [comment]
I am going to try and find a way to revert to the previous behavior without having compile-time dependencies on the private API. I am ashamed to say I did not pay close enough attention to this issue and did not think that testing for which parameters are passed to the application was very useful - so I am sorry for that. I will try and fix this ASAP.

**Comment by brcolow** [comment]
@VeryLazyBoy By the way, would you happen to have an example of a failing test that I can use as a regression test to make sure this doesn't happen again? Thanks!

**Comment by brcolow** [comment]
Oh, I think I understand better now. You were not actually /testing/ the parameters, but in your application you had:

```java
  private String getApplicationParameter(String parameterName) {
        Map<String, String> applicationParameters = getParameters().getNamed();
        return applicationParameters.get(parameterName);
    }
```

and thus when testing your application with TestFX this will fail with NPE. I get it now. This is quite a serious regression and I am working on a fix. Version 4 isn't `alpha` for no reason 👶 !

**Comment by VeryLazyBoy** [comment]
@brcolow , Yeah, you are right. The problem is failure with NPE when testing my application. I am sorry that I did not express the issue clearly. Really thanks for your attention for this issue and wish TestFX getting better and better!
