### ISSUE TITLE
Testing A .exe 

### ISSUE THREAD

**Issue by EssexMK** [TestFX/TestFX#402]
Hi Everyone, So My Question Is : "How Can We Test A .exe Using TestFx ?" The Main Problem Is To Get The Main Class Of .exe (It Can Be Runnable As a Process ).
Thank's

**Comment by deen13** [comment]
Why do you want to test an executable?
Why convert a Java program into an executable?

**Comment by EssexMK** [comment]
Sorry 4 beeing Late It's Because I Have Only A .exe So Is It Possible

**Comment by hastebrot** [comment]
TestFX runs tests doing something similar what `Application.launch()` does. This means it needs direct access to your `Application`, i.e. in the same JVM instance.

So the answer is no, unless we find a way to externally access the objects of your running application, and I expect major changes to the TestFX code in order to archive this.

**Comment by brcolow** [comment]
Allowing for testing an external executable file is out of scope for the TestFX project.
