### ISSUE TITLE
How do I test staging?

### ISSUE THREAD

**Issue by SirMathhman** [TestFX/TestFX#497]
I saw from the tutorial that in the @Start method, the stage is supplied. However, what if I wanted an @Test method that uses a Stage and/or tests that the stage properly displays?

**Comment by JordanMartinez** [comment]
See FXToolkit's static methods. For example, [`registerPrimaryStage(Supplier<Stage> stageSupplier)`](https://github.com/TestFX/TestFX/blob/4489c117925325bef05b56c56f2bf9caf325cc96/subprojects/testfx-core/src/main/java/org/testfx/api/FxToolkit.java#L118-L128)

**Comment by SirMathhman** [comment]
What about FileChooser and DirectoryChoosers? @JordanMartinez

**Comment by JordanMartinez** [comment]
I don't think those are supported.

**Comment by SirMathhman** [comment]
Hm. Well, that's a pain in the neck.

**Comment by brcolow** [comment]
Testing FileChoosers and DirectoryChoosers is difficult because they are handled by the operating system JavaFX is running on. Depending on how you want to test them, some workarounds can be used. It might make the most sense however to simply mock a FileChooser/DirectoryChooser with a mocking library such as Mockito because you only want to test *your* code, and assuming that the file choosing works properly is JavaFX's job.

**Comment by SirMathhman** [comment]
I see. Thanks!
