### ISSUE TITLE
 java.lang.NoClassDefFoundError: javafx/application/Application when using <reuseForks>false</reuseForks>

### ISSUE THREAD

**Issue by stefanofornari** [TestFX/TestFX#587]
## Expected Behavior

fx tests ran

## Actual Behavior

If I configure surefire with reuseForks to false fx runner is not found.

Eg:

```
           <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.21.0</version>
                <configuration>
                    <includes>
                        <include>**/BG*.java</include>
                        <include>**/BugFree*.java</include>
                        <include>**/*BugFree.java</include>
                        <include>**/*BF.java</include>
                    </includes>
                    <forkCount>1</forkCount>
                    <reuseForks>false</reuseForks>
                </configuration>
           </plugin>
```

## Specifications

  - Version: 4.0.13-alpha
  - Platform: Ubuntu linux, netbeans, maven

**Comment by brcolow** [comment]
Can you show the full stack trace?

**Comment by brcolow** [comment]
Something is wrong with the classpath in this setup, surefire can't find the JavaFX classes which are in the JDK. It doesn't seem like a TestFX issue specifically from looking at the stacktrace. What's the reason you want to have `reuseForks` set to false?

**Comment by mvsoder** [comment]
I was having trouble with memory leaks (I believe due to software rendering in monocle) so I switched to <code>reuseForks</code> set to false to avoid memory problems during testing. This greatly increased the test time but was at least stable enough to run through all the tests.

**Comment by liamsharp** [comment]
@brcolow We've got a bunch of configuration in our application that requires a restart. Running a test suite that requires say 20 different instances of our application to be started and stopped causes us to run out of memory.

I've spent a fair bit of time in visual VM tracking down why applications don't clean up and it seems there is a fair bit of static data in use in the JavaFX code that prevents this. For example, all instances of `Application` are stored in a static map in `com.sun.javafx.application.ParametersImpl` . It has a `registerParameters()` but no way to unregister. I've added a way to unregister using reflection, but it seems various other listeners etc all need to be unregistered as well. This approach means the `stop()` in my `Application` has to trigger a lot of unregistrations, stopping of JavaFx timers etc. This is really quite hard to get right, and not something we need for normal running of our applications. Starting each application for testing in the same VM also means that any static data only get initialised for the first instance, not the subsequent ones, which can triggers some frustrating issues.

So, given the above, we'd like to be able to ignore all this, have each test run in it's own fork.

Any suggestions on how to debug the issue?

**Comment by stefanofornari** [comment]
when classes have static methods/fields or multithreaded code you may want
to make sure the JVM is reastarted from scratch.

Ste

**Comment by brcolow** [comment]
I wish I could be of any help here, but I am not sure where to begin with this one. I have never really touched the TestFX "initialization" code wherein `Application`s are initialized and registered, and primary stages are setup and then cleaned up. I think it will require some deep diving into the TestFX source code with a debugger to have a chance to fix it. I'm sorry I'm essentially useless here.

**Comment by liamsharp** [comment]
Hi @brcolow no worries, and thanks for your help. I've managed to boil this down ever further to just a surefire issue. I found:

https://issues.apache.org/jira/browse/SUREFIRE-1438

which details a workaround to use `additionalClasspathElements` to avoid this happening. eg:

```
          <additionalClasspathElements>
            <additionalClasspathElement>${java.home}/lib/ext/jfxrt.jar</additionalClasspathElement>
          </additionalClasspathElements>

```
I've updating that issue with my findings so hopefully this will work out of the box in a future release.

I'd suggest that this issue can be closed now as it's a surefire issue.

**Comment by Tibor17** [comment]
@stefanofornari 
@liamsharp 
@brcolow 
@mvsoder 
This problem is being discussed in two issues namely [SUREFIRE-1438](https://issues.apache.org/jira/browse/SUREFIRE-1438) and [SUREFIRE-1537](https://issues.apache.org/jira/browse/SUREFIRE-1537). We have the same problem with Arquillian when the static initializers are called twice. Once in plugin JVM process via `IsolatedClassLoader` and second time in forked JVM. Therefore this issue is workaround with `reuseForks=false, forkCount=1` because then the `IsolatedClassLoader` is not in use. The `IsolatedClassLoader` again loads classes for test-ClassLoader again and filters those which should be run in parallel forked JVMs. The `IsolatedClassLoader` does not load SystemClassLoader staff but the parent (Bootstrap) and it looks to me that the whole problem with JavaFX is that the `jfxrt.jar` is not available in Bootstrap.

I want to fix all these issue with same root cause in version 3.0.
I am convinced that making filtering in forked JVM would be the trick to do but the problem that the communication protocol between in-process and forked JVM were not ready for this. So I made almost complete fix in branch `SUREFIRE-1222` and [SUREFIRE-1559](https://issues.apache.org/jira/browse/SUREFIRE-1559).
