### ISSUE TITLE
Menu Accelerator using KeyCombination.SHORTCUT_DOWN doesn't work on macOS

### ISSUE THREAD

**Issue by liamsharp** [TestFX/TestFX#589]
## Expected Behaviour 

Adding an accelerator to a `MenuItem`, eg:

`openMenuItem.setAccelerator(new KeyCodeCombination(KeyCode.O, KeyCombination.SHORTCUT_DOWN));`

should be triggered by the following testFx code:

`robotContext().getTypeRobot().push(new KeyCodeCombination(KeyCode.O, KeyCombination.SHORTCUT_DOWN));`

but it's not. This works on Windows 10 & Ubuntu 16.04, but fails macOS 10.13.5

## Actual Behavior

Example project here:

https://github.com/liamsharp/testfx-accelerators/

Run:

`mvn clean test`

and you get a failure. If you change `AppTest` to use `KeyCombination.META_DOWN` and it works.

## Specifications

  - Version: 10.13.5
  - Platform: macOS

**Comment by brcolow** [comment]
I believe this is related to the fact that we process a `SHORTCUT` key differently on macOS than on Windows and Linux, see:

https://github.com/TestFX/TestFX/blob/eab873525935da235e66ddec59cb7f3ea3a8fe3f/subprojects/testfx-core/src/main/java/org/testfx/robot/impl/KeyboardRobotImpl.java#L78

This was added to address https://github.com/TestFX/TestFX/issues/290 - how can we keep that fix while making sure it also works for this use-case?

**Comment by Ortner** [comment]
Instead of opening a new issue, I'm joining this one.

## Issue
Command-Key handling on mac. On my platform the tests in `ShortcutKeyTest.java` on master fail. I guess they are running on Travis somehow. There are pretty much issues relating to the mac `SHORTCUT` key (#589, #436, #590).

Per specification, the `COMMAND`-Key on Mac does map to the `META` KeyCode in Java. The CONTROL key on Windows, well to the `CONTROL` KeyCode. Both Map to the `SHORTCUT` KeyCode in Java. The `SHORTCUT` is a generated Property by the JVM (a virtual, non existing key), it may not be used as real input. 

## Behaviour of KeyCodes on macOS

- `press(KeyCode.META)` - Received by KeyEvent: `KeyCode.COMMAND`, `e.isShortShortcutDown()`: true
- `press(KeyCode.SHORTCUT)` - Received by KeyEvent: `KeyCode.A`, `e.isShortShortcutDown()`: false (That's where all those 'a's in my text editor come from after running TestFX-Tests)
- `press(KeyCode.CONTROL)` - Received by KeyEvent: `KeyCode.Ctrl`, `e.isShortShortcutDown()`: false
- `press(KeyCode.COMMAND)` - Received by KeyEvent: nothing at all

## Expected Behavior

- `SHORTCUT+A`, `SHORTCUT+C`, `SHORTCUT+V` (...) should work
- the method KeyEvent.isShortcutDown() should actually return true while pressed (currently it returns false)
- KeyCode Combinations should work (e.g. robotContext().getTypeRobot().push(new KeyCodeCombination(KeyCode.O, KeyCombination.SHORTCUT_DOWN));) (#590, #589)


## Actual Behavior

Test as is fails :-)

## Specifications

  - Version: Master
  - Platform: macOS High Sierra 10.13.6
 - Java: 1.8.0_152-b16

PR follows...
