### ISSUE TITLE
atPosition fails with windows 10 screen zoom different from 100%

### ISSUE THREAD

**Issue by antoniovazquezaraujo** [TestFX/TestFX#628]
## Expected Behavior
The method `atPosition` must locate a % of a node, from 0.0 to 1.0, and it works fine with normal windows zoom of 100%

## Actual Behavior
With zoom at 125%, `atPosition ` with 1.0, 0.5, fails locating the right border of the node, as it goes off by some pixels. To make it work, you need to send exactly 1.05 as first parameter.

## Specifications

  - Version:
testfx 3.1.2
  - Platform:
windows 10

**Comment by brcolow** [comment]
Unfortunately legacy TestFX (version 3) is no longer supported - can you entertain the possibility of switching to TestFX 4?

**Comment by brcolow** [comment]
Closing for now as legacy TestFX [is deprecated and no longer supported](https://github.com/TestFX/TestFX#user-content-testfx-legacy-deprecated). Please re-open if you experience the same issue on TestFX 4.

**Comment by antoniovazquezaraujo** [comment]
Oh, sorry. The testfx version is really 4.0.13-alpha.

**Comment by brcolow** [comment]
Okay, then this should be fixed on `master`. I will cut a new release tomorrow.

**Comment by antoniovazquezaraujo** [comment]
And I dont know how to reopen the cuestion. Maybe I need to create another one with the same text? Or simple make this comment. Sorry for the inconvenience.

**Comment by brcolow** [comment]
If you want to use or test the fixed version of TestFX before an official release you can use [jitpack](jitpack.io).

**Comment by brcolow** [comment]
Version [4.0.15-alpha](https://github.com/TestFX/TestFX/releases/tag/v4.0.15-alpha) was released today. It should be synced with Maven Central in 24 hours. This is the first time I will be attempting to use the [deploy script](https://github.com/TestFX/TestFX/blob/master/.ci/deploy.sh) to sync with Maven Central instead of the Bintray web UI so it may not work. If that's the case I will have to manually sync tomorrow and it may take an additional 24 hours. I'd like to wait before manually syncing so that I know if the deploy script is working or not 😄.

**Comment by brcolow** [comment]
Version 4.0.15-alpha has been synced to [Maven Central](http://central.maven.org/maven2/org/testfx/testfx-core/4.0.15-alpha/). Let me know if you can still reproduce your error with the latest version.
