### ISSUE TITLE
Allow custom stage to be set on GuiTest

### ISSUE THREAD

**Issue by aalmiray** [TestFX/TestFX#66]
Currently `GuiTest` creates a `Stage` as a convenience for developers. But what if I already have a `Stage` instance setup? I'd love to be able to tell GuiTest to use that Stage (and hence it's root node) instead of what's done today. This may be related to https://github.com/SmartBear/TestFX/pull/39 asthis feature further enables reusability and composition.

**Comment by Baba-sadou** [comment]
Hi,
I would like to  use TestFx for testing an application that has a preloader.
i launch this application with this instruction in my Main Class :
 LauncherImpl.launchApplication(MainApp.class, MainSplash.class, args);
i have looked for functions in FxToolKit class that can do the same thing, but i haven't found any.
could you help me please ?

**Comment by hastebrot** [comment]
`LauncherImpl` does not support preloaders. You could implement support for preloaders youself, the functionality is in `launchApplicationWithArgs()` in `com.sun.javafx.application.LauncherImpl`. This methods calls `startToolkit()` which is problematic for testing, since we need to setup `Application`s multiple times, but starting the toolkit is only allowed once. This means we can't reuse this method for test setup, but we can copy parts of this method to launch preloaders and the application.

**Comment by Baba-sadou** [comment]
ok, thinks

**Comment by kayz1** [comment]
@hastebrot any news on launching applications with preloaders? Is there any example, anywhere? Thx

**Comment by hastebrot** [comment]
@kayz1 A starting point would be here: https://github.com/javafxports/openjdk-jfx/blob/jfx-12/modules/javafx.graphics/src/main/java/com/sun/javafx/application/LauncherImpl.java#L135-L157

**Comment by kayz1** [comment]
@hastebrot I managed to get it running with preloader, simply by setting 
`System.setProperty("javafx.preloader", ApplicationPreloader.class.getCanonicalName());`

Now I'am puzzled by cycles (testing, application). What is the correct approach for managing entire application, from start to shutdown.

Where do I start the app? In init - with launch(app.class)?
In @BeforeStart static method?
Can I stop the application for every test?

Any help or direction would be much appreciated.
