### ISSUE TITLE
Question: release planned for TestFX 4?

### ISSUE THREAD

**Issue by Skycode95** [TestFX/TestFX#747]
Hi,

Lastest release is for TestFX 3 (v3.1.2) and there is only pre-releases for TestFX 4. Is it possible to have a new release for TestFX 4?

Thanks.

**Comment by io7m** [comment]
Getting the impression that this project is dead. No commits since early 2021, and even that was just to fix a license header.

**Comment by mvsoder** [comment]
@hastebrot, @minisu and @svenruppert, what help would you like for TextFX and Monocle. I would like to see TestFX 4 get out the door and get some newer versions of Monocle get published. I'm happy to help if that's what it takes.

**Comment by svenruppert** [comment]
We can work on this.. your help is welcome :-) Von meinem iPhone gesendetAm 15.05.2023 um 20:37 schrieb Mark Soderquist ***@***.***>:﻿
@hastebrot, @minisu and @svenruppert, what help would you like for TextFX and Monocle. I would like to see TestFX 4 get out the door and get some newer versions of Monocle get published. I'm happy to help if that's what it takes.

**Comment by mvsoder** [comment]
@svenruppert I've forked the repos. Is there a contributors onboarding document? If not, where would you like me to start?

**Comment by svenruppert** [comment]
Hi Mark,
I am planning to restructure the project to bring it alive again.
You are welcome to help me here with your ideas.

For this, I am planning new features, bug fixes, and so on.
But I am in a hospital right now, finishing my cancer therapy.
This will slow down from time to time, just to give you a. heads-up ;-)

What is a messenger you are available at? So that no everything is lost in
emails?
Otherwise, I would use Space or similar to reorg the project before we are
shifting back to GitHub.
I just, don´t want to mess GitHub up.

Can you give me a bit more background about you?


Cheers Sven




--------------------------------------------------
Sven Ruppert - Germany
web:https://svenruppert.com
twitter: https://twitter.com/SvenRuppert @SvenRuppert
linkedin: https://www.linkedin.com/in/svenruppert



Am Di., 16. Mai 2023 um 17:27 Uhr schrieb Mark Soderquist <
***@***.***>:

**Comment by mvsoder** [comment]
@Skycode95 and @io7m TestFX 4 is already quite stable even though it still has an `alpha` label in the version. We are working toward a non-alpha release soon. Stay tuned.
