### ISSUE TITLE
java.lang.IllegalAccessError: module javafx.graphics does not export com.sun.javafx.application to unnamed module

### ISSUE THREAD

**Issue by sdorof1** [TestFX/TestFX#751]
I got the exception when run TestFX tests from Eclipse:

`java.lang.RuntimeException: java.lang.IllegalAccessError: class org.testfx.toolkit.impl.ToolkitServiceImpl (in unnamed module @0x28586) cannot access class com.sun.javafx.application.ParametersImpl (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.application to unnamed module @0x28586`

If I run the tests by gradle the exception does not throws.
As a workaround, it is need to add

`--add-exports javafx.graphics/com.sun.javafx.application=ALL-UNNAMED`

to vmargs of eclipse's run configuration. But it is need to do for EACH tests and this is very confusing (or I does not know as to set it for all tests at once).

**Comment by MarekChr** [comment]
I have same issue on IntelliJ 2023.1 while using Liberica JDK 17 (jdk includes javafx) and Maven 3.8.1.

**Comment by hastebrot** [comment]
As far as I know this should be an issue for all JRE/JDK that introduced modules (JDK 9 as far as I remember).

https://github.com/TestFX/TestFX/commit/dcc64b870d2eb024a72c40150e97367d31c1733a shows that we have to access `com.sun.javafx.application` package.

I you try to find a solution, maybe you can provide a custom `ToolkitService` and just not use `com.sun.javafx.application.ParametersImpl`. I'm not sure if this works, however.

**Comment by mvsoder** [comment]
I believe PR https://github.com/TestFX/TestFX/pull/757 will resolve this issue.

**Comment by droidkfx** [comment]
Using the latest version, this does not appear to be resolved. 

Junit Version: 5.9.3
Java Version: 20
testfx-junit5: 4.0.16-alpha

`java.lang.IllegalAccessError: class org.testfx.toolkit.impl.ToolkitServiceImpl (in unnamed module @0x2473b9ce) cannot access class com.sun.javafx.application.ParametersImpl (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.application to unnamed module @0x2473b9ce`

This workaround still works but is painful.

`--add-exports javafx.graphics/com.sun.javafx.application=ALL-UNNAMED`

**Comment by mvsoder** [comment]
You are correct. This fix will be available in 4.0.17 and later.

**Comment by droidkfx** [comment]
Ahh, that makes sense. Do you have a release timeline for the minor version bump?

**Comment by mvsoder** [comment]
The timeline is "as soon as possible". However, we are having to work through some technical issues while we get the project going again. I think we all want 4.0.17 as soon as we can since it has several bug fixes.
